fix: use TryFrom instead of deprected from_i32
error: use of deprecated associated function `shared::net_msg::reject::RejectReason::from_i32`: Use the TryFrom<i32> implementation instead
   --> tools/metrics/src/main.rs:365:44
    |
365 | ...                   &RejectReason::from_i32(r.reason).unwrap().to_string(),
    |                                      ^^^^^^^^
    |
note: the lint level is defined here
   --> tools/metrics/src/main.rs:1:38
    |
1   | #![cfg_attr(feature = "strict", deny(warnings))]
    |                                      ^^^^^^^^
    = note: `#[deny(deprecated)]` implied by `#[deny(warnings)]`

error: could not compile `metrics` (bin "metrics") due to 1 previous error